/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{html,js,svelte,ts}"],
	theme: {
		extend: {},
	},
	plugins: [require("daisyui")],
	daisyui: {
		themes: [
			{
				TheatreX: {
					primary: "#ffffff",
					secondary: "#152747",
					accent: "#a463ee",
					neutral: "#171618",
					"neutral-content": "#e1b66b",
					"base-100": "#09090b",
					"base-200": "#171618",
					"base-300": "#2e2d2f",
					"base-content": "#dca54c",
					info: "#66c6ff",
					success: "#87d039",
					warning: "#e2d562",
					error: "#ff6f6f",
				},
			},
			"light",
			"dark",
			"cupcake",
			"bumblebee",
			"emerald",
			"corporate",
			"synthwave",
			"retro",
			"cyberpunk",
			"valentine",
			"halloween",
			"garden",
			"forest",
			"aqua",
			"lofi",
			"pastel",
			"fantasy",
			"wireframe",
			"black",
			"luxury",
			"dracula",
			"cmyk",
			"autumn",
			"business",
			"acid",
			"lemonade",
			"night",
			"coffee",
			"winter",
		],
	},
};
